# Generated by Django 5.1.4 on 2025-01-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=221, null=True)),
                ('last_name', models.CharField(blank=True, max_length=221, null=True)),
                ('username', models.CharField(blank=True, max_length=221, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
    ]
